site_name: CS DEPARTMENT SYLLABY PAGE

nav:
  - Syllaby: index.md
  - Guide: guide.md

theme:
  name: material
  logo: 'images/logo2.png'
  favicon: 'images/logo.png'
  palette:
    scheme: default
    primary: 'green'
    accent: 'light green'